<?php

return [
    'ApplicationConstants::PROJECT_NAMESPACE' => 'KernelConstants::PROJECT_NAMESPACE',
    'ApplicationConstants::APPLICATION_SPRYKER_ROOT' => 'KernelConstants::SPRYKER_ROOT',
    'ApplicationConstants::CORE_NAMESPACES' => 'KernelConstants::CORE_NAMESPACES',
    'ApplicationConstants::ERROR_LEVEL' => 'ErrorHandlerConstants::ERROR_LEVEL',
    'ApplicationConstants::SET_REPEAT_DATA' => 'ZedRequestConstants::SET_REPEAT_DATA',
    'ApplicationConstants::TRANSFER_USERNAME' => 'ZedRequestConstants::TRANSFER_USERNAME',
    'ApplicationConstants::TRANSFER_PASSWORD' => 'ZedRequestConstants::TRANSFER_PASSWORD',
    'ApplicationConstants::JENKINS_BASE_URL' => 'SetupConstants::JENKINS_BASE_URL',
    'ApplicationConstants::JENKINS_DIRECTORY' => 'SetupConstants::JENKINS_DIRECTORY',
    'ApplicationConstants::DISPLAY_ERRORS' => 'ErrorHandlerConstants::DISPLAY_ERRORS',
    'ApplicationConstants::STORE_PREFIX' => 'KernelConstants::STORE_PREFIX',
    'ApplicationConstants::ZED_TWIG_OPTIONS' => 'TwigConstants::ZED_TWIG_OPTIONS',
    'ApplicationConstants::YVES_TWIG_OPTIONS' => 'TwigConstants::YVES_TWIG_OPTIONS',
    'ApplicationConstants::NAVIGATION_CACHE_ENABLED' => 'ZedNavigationConstants::ZED_NAVIGATION_CACHE_ENABLED',
    'ApplicationConstants::LOG_LEVEL' => 'LogConstants::LOG_LEVEL',
    'ApplicationConstants::YVES_ERROR_PAGE' => 'ErrorHandlerConstants::YVES_ERROR_PAGE',
    'ApplicationConstants::ZED_ERROR_PAGE' => 'ErrorHandlerConstants::ZED_ERROR_PAGE',
    'ApplicationConstants::TRANSFER_DEBUG_SESSION_FORWARD_ENABLED' => 'ZedRequestConstants::TRANSFER_DEBUG_SESSION_FORWARD_ENABLED',
    'ApplicationConstants::TRANSFER_DEBUG_SESSION_NAME' => 'ZedRequestConstants::TRANSFER_DEBUG_SESSION_NAME',
    'ApplicationConstants::ZED_API_SSL_ENABLED' => 'ZedRequestConstants::ZED_API_SSL_ENABLED',
    'ApplicationConstants::ZED_SHOW_EXCEPTION_STACK_TRACE' => 'ErrorHandlerConstants::ERROR_RENDERER',
    'ApplicationConstants::YVES_SHOW_EXCEPTION_STACK_TRACE' => 'ErrorHandlerConstants::ERROR_RENDERER',
];
